CREATE TABLE Registered_User (
  userID INT PRIMARY KEY AUTO_INCREMENT,
  userImg VARCHAR(255),
  userName VARCHAR(255) NOT NULL,
  userEmail VARCHAR(255) NOT NULL,
  userPass VARCHAR(255) NOT NULL,
  userBio TEXT,
  favID INT
);

CREATE TABLE Admin (
  adminID INT PRIMARY KEY AUTO_INCREMENT,
  adminName VARCHAR(255) NOT NULL,
  adminPass VARCHAR(255) NOT NULL
);

CREATE TABLE Meal_Difficulty (
  diffID INT PRIMARY KEY AUTO_INCREMENT,
  mealDiff VARCHAR(255) NOT NULL
);

CREATE TABLE Meal_Type (
  typeID INT PRIMARY KEY AUTO_INCREMENT,
  mealType VARCHAR(255) NOT NULL
);

CREATE TABLE Recipe (
  recipeID INT PRIMARY KEY AUTO_INCREMENT,
  recipeImg VARCHAR(255),
  recipeName VARCHAR(255) NOT NULL,
  recipeIngred TEXT NOT NULL,
  recipeDesc TEXT NOT NULL,
  recipeDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  recipeStatus VARCHAR(255) NOT NULL,
  userID INT,
  diffID INT,
  typeID INT,
  favID INT,
  feedbackID INT
);

CREATE TABLE Favourite (
  favID INT PRIMARY KEY AUTO_INCREMENT,
  userID INT,
  recipeID INT
);

CREATE TABLE Rating (
  ratingID INT PRIMARY KEY AUTO_INCREMENT,
  ratingNum INT NOT NULL
);

CREATE TABLE Feedback (
  feedbackID INT PRIMARY KEY AUTO_INCREMENT,
  userID INT,
  recipeID INT,
  ratingID INT,
  comment TEXT,
  feedbackDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);